"""Judge prompt templates used by main.py.

Placeholders ({gate_criteria}, {components_guide}, {marking_rules_block}, ...) are filled by the format_* helpers in main.py from the rubric JSON;
{marking_rules_block} is expected to bring its own trailing newline.
"""

# 1. Pointwise scoring (0-10 against the rubric)
PROMPT_SCORING = """You are an expert geological evaluator. Your task is to evaluate the quality of the response generated by an AI model against a strict scoring rubric and assign a score out of 10.

# Evaluation
## Metric Definition
You will be assessing the accuracy, correctness, and completeness of the response and its application of geological principles.

## Criteria & Minimum Threshold (Gate)
{gate_criteria}

## Rating Rubric & Components
{components_guide}

## Concept Control
- Required concepts (must be present or conceptualized): {required_keywords}
- Indicative terms (vocabulary only — these earn NO marks on their own): {bonus_keywords}

## Accepted Name Variants (treat as equivalent — do NOT penalize spelling/transliteration differences)
{transliteration_variants}

## Distractors — Do NOT Credit
{distractors}

{marking_rules_block}## Evaluation Steps
STEP 1: Check the Gate/minimum correctness threshold criteria. If the response fails this threshold, the score MUST be 0. No partial credit leaks through. A response that both asserts and denies the gate claim has not unambiguously demonstrated it — the Gate fails.
STEP 2: If the Gate passes, evaluate the response against each defined Component to award non-overlapping credits. A component marked [Binary] is all-or-nothing: award its full points or zero, never part. A statement that directly contradicts a component's required claim means that component is not demonstrated — award it zero.
STEP 3: Check the required concepts against the components they belong to. Indicative terms carry no marks by themselves — never award points for their presence alone. Treat any name listed under Accepted Name Variants as equivalent.
STEP 4: Ensure reasoning components require demonstrated logic, not keyword matching alone.
STEP 5: Withhold credit for anything matching the Distractors — Do NOT Credit list.
STEP 6: Do not treat a response as self-contradictory when it presents competing interpretations explicitly as alternatives and evaluates them correctly — that is sound reasoning, not hedging. Correct material that was not asked for is neutral: it neither adds nor subtracts.
STEP 7: Sum the credits and cap the final score at 10.

# Inputs
## User Prompt
{question}

## Reference Answer
{model_answer}

## Underlying Principle
{principle}

## AI-generated Response to Evaluate
{response}

# Output Format
Provide your step-by-step reasoning based on the Evaluation Steps.
Then end your response with one fenced JSON block reporting the result in exactly this shape:

```json
{{
  "gate_passed": true,
  "gate_reason": "one sentence on why the gate passed or failed",
  "components": [
    {{"id": "C1", "awarded": 3, "maximum": 3, "reason": "what earned or withheld this credit"}}
  ],
  "total": 8,
  "adjudication_required": false,
  "adjudication_note": null
}}
```

JSON rules:
- List every component from the Rating Rubric & Components, in order, with its exact id and its maximum points.
- "awarded" and "maximum" are whole numbers. "total" must equal the sum of all "awarded" values.
- If the Gate fails: "gate_passed" is false, every "awarded" is 0, and "total" is 0.
- Set "adjudication_required" to true only when the response may deserve credit that cannot be verified from the material above (e.g. an unexpected but plausibly valid approach); explain in "adjudication_note", otherwise leave it null."""


# 2. Preference ranking (pairwise A-vs-B compare)
PROMPT_PREFERENCE = """You are an expert geological evaluator. Compare two AI assistants' answers to the same geological question.

# Evaluation
## Metric Definition
Compare both answers against the reference to identify any mistakes, missing information, or hallucinations. Consider relevance, accuracy, conciseness, and geological reasoning. Named entities (suite names, occurrence names, fault names, specific values) are the primary discriminators.

Treat the following as equivalent spellings — do NOT penalize transliteration differences:
{transliteration_variants}

## Criteria
The responses should accurately capture the underlying geological principles and model answer provided below.

# Evaluation Reference
## Model Answer Reference
{model_answer}

## Underlying Principle
{principle}

# Inputs
## User Prompt
{question}

## Assistant A's Answer
{answer_a}

## Assistant B's Answer
{answer_b}

# Output Format
Write a brief evaluation explaining which answer is better and why based on the criteria.
Then on the very last line, output the final verdict strictly using one of these tokens:
- Assistant A is significantly better: [[A>>B]]
- Assistant A is slightly better: [[A>B]]
- Tie, relatively the same: [[A=B]]
- Assistant B is slightly better: [[B>A]]
- Assistant B is significantly better: [[B>>A]]"""
